import imagePath from "../assets/imagePath";

export const ListProduct = [
  {
    id: 1,
    name: "Apple Watch Ultra",
    newPrice: 2500000,
    oldPrice: 3000000,
    img: imagePath.watch_2,
    href: "",
    rating: 3,
    more: "lotemmamuidwdyhuasdaoiwdujasoduiwjdo",
    percent: 30,
  },
  {
    id: 2,
    name: "Iphone 14 Pro Max",
    newPrice: 1500000,
    oldPrice: 2500000,
    img: imagePath.ip14,
    href: "",
    rating: 3,
    more: "lotemmamuidwdyhuasdaoiwdujasoduiwjdo",
    percent: 30,
  },
  {
    id: 3,
    name: "Galaxy S23 Ultra",
    newPrice: 900000,
    oldPrice: 1000000,
    img: imagePath.s23,
    href: "",
    rating: 3,
    more: "lotemmamuidwdyhuasdaoiwdujasoduiwjdo",
    percent: 30,
  },
  {
    id: 4,
    name: "Galaxy S23 Ultra",
    newPrice: 900000,
    oldPrice: 1000000,
    img: imagePath.s23,
    href: "",
    rating: 3,
    more: "lotemmamuidwdyhuasdaoiwdujasoduiwjdo",
    percent: 30,
  },
  {
    id: 5,
    name: "Iphone 14 Pro Max",
    newPrice: 1500000,
    oldPrice: 2500000,
    img: imagePath.ip14,
    href: "",
    rating: 3,
    more: "lotemmamuidwdyhuasdaoiwdujasoduiwjdo",
    percent: 30,
  },
  {
    id: 6,
    name: "Apple Watch Ultra",
    newPrice: 2500000,
    oldPrice: 3000000,
    img: imagePath.watch_2,
    href: "",
    rating: 3,
    more: "lotemmamuidwdyhuasdaoiwdujasoduiwjdo",
    percent: 30,
  },
];

export const ListLatopProduct = [
  {
    id: 1,
    name: "Macbook",
    newPrice: 2500000,
    oldPrice: 3000000,
    img: imagePath.macbook,
    href: "",
    rating: 3,
    more: "testetset",
    percent: 30,
  },
  {
    id: 2,
    name: "Macbook",
    newPrice: 1500000,
    oldPrice: 2500000,
    img: imagePath.macbook,
    href: "",
    rating: 3,
    more: "testetset",
    percent: 30,
  },
  {
    id: 3,
    name: "Macbook",
    newPrice: 900000,
    oldPrice: 1000000,
    img: imagePath.macbook,
    href: "",
    rating: 3,
    more: "testetset",
    percent: 30,
  },
  {
    id: 4,
    name: "Macbook",
    newPrice: 900000,
    oldPrice: 1000000,
    img: imagePath.macbook,
    href: "",
    rating: 3,
    more: "testetset",
    percent: 30,
  },
  {
    id: 5,
    name: "Macbook",
    newPrice: 1500000,
    oldPrice: 2500000,
    img: imagePath.macbook,
    href: "",
    rating: 3,
    more: "testetset",
    percent: 30,
  },
  {
    id: 6,
    name: "Macbook",
    newPrice: 2500000,
    oldPrice: 3000000,
    img: imagePath.macbook,
    href: "",
    rating: 3,
    more: "testetset",
    percent: 30,
  },
];

export const ListSale = [
  {
    name: "Apple Watch Ultra",
    percent: "25",
    src: imagePath.watch_2,
    color: "#cbecff",
    href: "",
  },
  {
    name: "Iphone 14 Pro Max",
    percent: "10",
    src: imagePath.ip14,
    color: "#FFF3D2",
    href: "",
  },
  {
    name: "Macbook",
    percent: "15",
    src: imagePath.s23,
    color: "#FFE9EA",
    href: "",
  },
];
